export const userData = [
  {
    name: "Jan",
    "Active User": 4000,
  },
  {
    name: "Feb",
    "Active User": 3000,
  },
  {
    name: "Mar",
    "Active User": 2000,
  },
  {
    name: "Apr",
    "Active User": 2780,
  },
  {
    name: "May",
    "Active User": 1890,
  },
  {
    name: "Jun",
    "Active User": 2390,
  },
  {
    name: "Jul",
    "Active User": 5490,
  },
  {
    name: "Aug",
    "Active User": 1490,
  },
  {
    name: "Sep",
    "Active User": 2490,
  },
  {
    name: "Oct",
    "Active User": 1090,
  },
  {
    name: "Nov",
    "Active User": 4490,
  },
  {
    name: "Dec",
    "Active User": 3490,
  },
];
export const productData = [
  {
    name: "Jan",
    Sales: 4000,
  },
  {
    name: "Feb",
    Sales: 3000,
  },
  {
    name: "Mar",
    Sales: 5000,
  },
];

export const userRows = [
  {
    id: 1,
    username: "Jon Snow",
    avater: "./imgs/pp2.png",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "£120.00",
  },
  {
    id: 2,
    username: "Jon Snow",
    avater: "./imgs/pp2.png",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "£120.00",
  },
  {
    id: 3,
    username: "Jon Snow",
    avater: "./imgs/pp2.png",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "£120.00",
  },
  {
    id: 4,
    username: "Jon Snow",
    avater: "./imgs/pp2.png",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "£120.00",
  },
  {
    id: 5,
    username: "Jon Snow",
    avater: "./imgs/pp2.png",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "£120.00",
  },
  {
    id: 6,
    username: "Jon Snow",
    avater: "./imgs/pp2.png",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "£120.00",
  },
  {
    id: 7,
    username: "Jon Snow",
    avater: "./imgs/pp2.png",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "£120.00",
  },
  {
    id: 8,
    username: "Jon Snow",
    avater: "./imgs/pp2.png",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "£120.00",
  },
  {
    id: 9,
    username: "Jon Snow",
    avater: "./imgs/pp2.png",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "£120.00",
  },
  {
    id: 10,
    username: "Jon Snow",
    avater: "./imgs/pp2.png",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "£120.00",
  },
];

export const productRows = [
  {
    id: 1,
    name: "Novelty TShirt",
    img: "./imgs/shirt1.png",
    stock: 123,
    status: "active",
    price: "£120.00",
  },
  {
    id: 2,
    name: "Novelty TShirt",
    img: "./imgs/shirt1.png",
    stock: 123,
    status: "active",
    price: "£120.00",
  },
  {
    id: 3,
    name: "Novelty TShirt",
    img: "./imgs/shirt1.png",
    stock: 123,
    status: "active",
    price: "£120.00",
  },
  {
    id: 4,
    name: "Novelty TShirt",
    img: "./imgs/shirt1.png",
    stock: 123,
    status: "active",
    price: "£120.00",
  },
  {
    id: 5,
    name: "Novelty TShirt",
    img: "./imgs/shirt1.png",
    stock: 123,
    status: "active",
    price: "£120.00",
  },
  {
    id: 6,
    name: "Novelty TShirt",
    img: "./imgs/shirt1.png",
    stock: 123,
    status: "active",
    price: "£120.00",
  },
  {
    id: 7,
    name: "Novelty TShirt",
    img: "./imgs/shirt1.png",
    stock: 123,
    status: "active",
    price: "£120.00",
  },
  {
    id: 8,
    name: "Novelty TShirt",
    img: "./imgs/shirt1.png",
    stock: 123,
    status: "active",
    price: "£120.00",
  },
  {
    id: 9,
    name: "Novelty TShirt",
    img: "./imgs/shirt1.png",
    stock: 123,
    status: "active",
    price: "£120.00",
  },
  {
    id: 10,
    name: "Novelty TShirt",
    img: "./imgs/shirt1.png",
    stock: 123,
    status: "active",
    price: "£120.00",
  },
];
