import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Tunji",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: "1",
      name: "Kids Pull&Bear Jumper",
      slug: "Pull&Bear Jumper",
      keygen: "Kid KD3569",
      gender: "Female",
      size: ["XS", "S", "M", "L", "XL", "XXL"],
      price: 14.99,
      countInStock: 0,
      brand: ["Abercrombie"],
      image: "/imgs/kid1.png",
      rating: 3.0,
      numReviews: 0,
    },
    {
      //_id: "2",
      name: "Men's Knitwear Offers",
      slug: "Men's Knitwear Offers",
      keygen: "Men BK3569",
      gender: "Male",
      size: ["XS", "S", "M", "L", "XL", "XXL"],
      price: 14.99,
      countInStock: 20,
      brand: "Fitch",
      image: "/imgs/shirt1.png",

      rating: 4.0,
      numReviews: 10,
    },
    {
      //_id: "3",
      name: "Women's Knitwear Offers",
      slug: "Women's-Knitwear-Offers",
      keygen: "Women WM3569",
      gender: "Female",
      size: ["XS", "S", "M", "L", "XL", "XXL"],
      price: 14.99,
      countInStock: 20,
      brand: "Adidas",
      image: "/imgs/women1.png",

      rating: 3.0,
      numReviews: 5,
    },
    {
      //_id: "4",
      name: "Men Casual Lizard",
      slug: "Men-Casual-Lizard",
      keygen: "Men BK3569",
      gender: "Male",
      size: ["XS", "S", "M", "L", "XL", "XXL"],
      price: 19.99,
      countInStock: 20,
      brand: "ASOS",
      image: "/imgs/shirt2.png",

      rating: 4.5,
      numReviews: 8,
    },
    {
      //_id: "5",
      name: "Harajuku Tshirt",
      slug: "Harajuku-Tshirt",
      keygen: "Kid KD3569",
      gender: "Male",
      size: ["XS", "S", "M", "L", "XL", "XXL"],
      price: 14.99,
      countInStock: 20,
      brand: "Cheap Monday",
      image: "/imgs/kid2.png",

      rating: 5.0,
      numReviews: 17,
    },
    {
      //_id: "6",
      name: "Women Casual Lizard",
      slug: "Women-Casual-Lizard",
      keygen: "Women WM3569",
      gender: "Female",
      size: ["XS", "S", "M", "L", "XL", "XXL"],
      price: 19.99,
      countInStock: 20,
      brand: ["Abercrombie"],
      image: "/imgs/women2.png",

      rating: 3.0,
      numReviews: 17,
    },
  ],
  settings: [
    {
      about: "Your About here",
      terms: "Your terms here",
      returns: "Your return here",
      privacy: "Your privacy here",
      currency: "GBP",
      currencySign: "£",
      tax: 14,
      shipping: 24,
      express: "Your express here",
      expressCharges: "Your express here",
      standard: "Your standard here",
      standardCharges: "Your standard charges here",
      facebook: "https://web.facebook.com/",
      twitter: "https://twitter.com/",
      youtube: "https://youtube.com/",
      instagram: "https://www.instagram.com/",
      pinterest: "https://www.pinterest.com/",
      webname: "SHOPMATE",
      bannerBackground:
        "https://res.cloudinary.com/dstj5eqcd/image/upload/v1673724164/banner2_l71yuh.png",
      sizeGuide: "size guidelines",
      reviewGuide: "review guidelines",
      navOne: "Women",
      navTwo: "Men",
      navThree: "Kids",
      navFour: "Shoes",
      navFive: "Brand",
    },
  ],
};

export default data;
